environment: dev
product: kub

registry: docker.tmp.io

image:
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

serviceAccount:
  create: false

ingress:
  hosts:
    - host: kubedash.local
      paths: []

resources: {}

frontend:
  enabled: false