{{- $releaseName := .Release.Name -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $releaseName }}
  labels:
    {{- include "kubedash.labels" . | nindent 4 }}
  annotations:
    cert-manager.io/cluster-issuer: roboca-issuer
    ingress.kubernetes.io/ssl-redirect: "true"
    ingress.kubernetes.io/custom-request-headers: "X-Pic-Product: kub"
spec:
  rules:
  {{- range .Values.ingress.hosts }}
  - host: {{ . | quote }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ $releaseName }}
          servicePort: 80
  {{- end }}
  tls:
    - hosts:
      {{- range .Values.ingress.hosts }}
      - {{ . | quote }}
      {{- end }}
      secretName: {{ $releaseName }}-tls
